#服务端口
server:
  port: 8004

spring:
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gwy123456
  jackson:
    #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
  #nacos的服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #redis
  redis:
    host: 47.113.144.42
    port: 6379
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

#mybatis-plus:
#  configuration:
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/buqi/educms/mapper/xml/*.xml
